before:
  hooks:
    - go mod download
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  hooks:
    pre: packr
    post: packr clean
  goos:
    - linux
    - darwin
    - windows
  ldflags:
    - -s -w -X github.com/k1LoW/tbls.version={{.Version}} -X github.com/k1LoW/tbls.commit={{.FullCommit}} -X github.com/k1LoW/tbls.date={{.Date}} -X github.com/k1LoW/tbls/version.Version={{.Version}}
archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: tbls
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/tbls
  description: 'tbls is a CI-Friendly tool for document a database, written in Go.'
  install: bin.install 'tbls'
