language: go
go:
  - 1.10.x
  - master
services:
  - docker
addons:
  apt:
    update: true
before_install:
  - go get github.com/xo/usql
  - go get github.com/jessevdk/go-assets-builder
  - make depsdev
  - docker-compose up -d
  - sleep 20s
script:
  - make test
  - make build
  - DIFF=`./tbls diff pg://postgres:pgpass@localhost:55432/testdb?sslmode=disable -a test/relations.yml ./sample/postgres` && if [ ! -z "$DIFF" ]; then echo "document does not match database." >&2 ; echo $DIFF; exit 1; fi
  - DIFF=`./tbls diff my://root:mypass@localhost:33306/testdb -a test/relations.yml ./sample/mysql` && if [ ! -z "$DIFF" ]; then echo "document does not match database." >&2 ; echo $DIFF; exit 1; fi
  - DIFF=`./tbls diff my://root:mypass@localhost:33308/testdb -a test/relations.yml ./sample/mysql8` && if [ ! -z "$DIFF" ]; then echo "document does not match database." >&2 ; echo $DIFF; exit 1; fi
after_script:
  - make cover
