language: go
go:
  - 1.11.x
  - master
services:
  - docker
addons:
  apt:
    update: true
env:
  - GO111MODULE=on
install:
  - echo $TRAVIS_GO_VERSION
  - sudo pip install codecov
  - make depsdev
  - docker-compose up -d
  - sleep 20s
script:
  - make ci
after_script:
  - codecov
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
