language: go
go:
  - 1.10.x
  - master
services:
  - docker
addons:
  apt:
    update: true
before_install:
  - go get github.com/xo/usql
  - go get github.com/jessevdk/go-assets-builder
  - make depsdev
  - docker-compose up -d
  - sleep 20s
script:
  - make test
  - make test_too_many_tables
after_script:
  - make cover
