language: go
go:
  - 1.11.x
  - master
services:
  - docker
addons:
  apt:
    update: true
before_install:
  - sudo pip install codecov
  - make depsdev
  - docker-compose up -d
  - sleep 20s
script:
  - make test
  - make test_too_many_tables
  - make test_json
after_script:
  - codecov
